export const POKEMON_SUCCESS = "POKEMON_SUCCESS";
export const POKEMON_FAIL = "POKEMON_FAIL";
export const LOADING_DATA = "LOADING_DATA";
export const POKEMON_DETAIL = "POKEMON_DETAIL";
export const POKEMON_ID = "POKEMON_ID";
export const POKEMON_TYPE = "POKEMON_TYPE";
export const POKEMON_FETCH_TYPE = "POKEMON_FETCH_TYPE";
